//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbitrader.GW2API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int pk { get; set; }
        public int id { get; set; }
        public int itemPK { get; set; }
        public System.DateTime loadDate { get; set; }
        public int recipePK { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
