//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbitrader.GW2API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int pk { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int level { get; set; }
        public string rarity { get; set; }
        public Nullable<int> vendor_value { get; set; }
        public Nullable<int> itemFlagPK { get; set; }
        public string icon { get; set; }
        public System.DateTime loadDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ItemFlag ItemFlag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
