//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbitrader.GW2API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFlag
    {
        public int pk { get; set; }
        public Nullable<int> flagPK { get; set; }
        public System.DateTime loadDate { get; set; }
        public Nullable<int> itemPK { get; set; }
    
        public virtual Flag Flag { get; set; }
        public virtual Item Item { get; set; }
    }
}
