//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbitrader.GW2API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.RecipeDisciplines = new HashSet<RecipeDiscipline>();
        }
    
        public int pk { get; set; }
        public int id { get; set; }
        public string type { get; set; }
        public int outputItemPK { get; set; }
        public Nullable<int> outputItemCount { get; set; }
        public Nullable<int> minRating { get; set; }
        public int ingredientsPK { get; set; }
        public System.DateTime loadDate { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeDiscipline> RecipeDisciplines { get; set; }
    }
}
