//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbitrader.GW2API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.RecipeDisciplines = new HashSet<RecipeDiscipline>();
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int pk { get; set; }
        public int id { get; set; }
        public string type { get; set; }
        public int outputItemPK { get; set; }
        public System.DateTime loadDate { get; set; }
        public int output_item_id { get; set; }
        public Nullable<int> output_item_count { get; set; }
        public Nullable<int> min_rating { get; set; }
    
        public virtual Item OutputItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeDiscipline> RecipeDisciplines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
